[context]
name = "non-empty-str"
version = "0.11.1"
url = "https://github.com/nekitdev/non-empty-str"

[formats]
title = "[{{version}}]({{url}}/tree/v{{version}}) ({{date}})"
fragment = "{{content}} ([#{{id}}]({{url}}/pull/{{id}}))"
